### ISSUE TITLE
Unable to set optional path for rsync installed from Macports

### ISSUE THREAD

**Issue by bunk3m** [rsyncOSX/Documentation#141]
Hello.
Thanks for building a very interesting front end to rsync.  I'm looking forward to trying it out but I can't get my rsync v3.1.2 installed via Macports to be set in the optional path.
which rsync give the path: /opt/local/bin/rsync
I believe the permissions are 744 and the owner is root and group admin.  I think this is the standard for Macports.
I am not able to add the path without an error.

**Comment by rsyncOSX** [comment]
Hmm, I will look into it. You should set only the path, /opt/local/bin (I am not using Macports, that is why RsyncOSX gives an error).. 
You can also try to open a terminal and do a ls -al /opt/local/bin to check if you can list the rsync command. RsyncOSX does a simple file check to see if rsync is installed in the given path..

![skjermbilde 2018-02-07 kl 07 09 18](https://user-images.githubusercontent.com/22427340/35901324-55574c5e-0bd6-11e8-88e4-176895e867f5.png)

**Comment by bunk3m** [comment]
Thanks!
I'm not sure if the update fixed it but entering `/opt/local/bin` allowed RsyncOSX to find the rsync 3.1.2 from Macports.
Thanks again!
